model_to_use: xgboost_baseline
columns:
  target: 'percentage_docks_available'
  useful: ['month', 'day', 'hour', 'ctx-4', 'ctx-3', 'ctx-2', 'ctx-1', 'lat', 'lon', 'altitude']
  categorical: ['month', 'day', 'hour']

preprocessing:
  bicing_cols: 
    - 'station_id'
    - 'last_reported'
    - 'num_bikes_available'
    - 'is_installed'
    - 'is_renting'

  station_cols:
    - 'station_id'
    - 'name'
    - 'lat'
    - 'lon'
    - 'capacity'
    - 'altitude'
  use_meteo_data: True
  fetch_data: True
  save_file: True
  output_name: bicing_dataset.csv

train:
  mlflow:
    tracking_uri: 'http://127.0.0.1:5000'
    mlflow_experiment: 'test_experiment'
    mlflow_run: 'test_run'
  tuning: 
    mode: 'standard' # can be standard or custom. If custom, create a new class inheriting from BaseModelTrainer and write a custom train method
    strategy: random # can be either random or grid
    n_iter: 2 # Only necessary for random strategy
    parameters:
      model__max_depth: [3]
      
    
pipeline:
  preprocess: False
  train: True
  

    