data_paths:
  bicing_data: 'ROOT/data/raw_data'
  meteo_data: 'ROOT/data/meteo_data'
  submission_data: 'ROOT/data/submission_data'
  processed_data: 'ROOT/datasets/'
  stations_to_use_path: 'ROOT'
  stations_info_path: 'ROOT/station_info.csv'


trainer_paths:
  best_model_path: 'ROOT/artifacts/best_model'
  models_path: 'ROOT/artifacts/models'
  transformers_path: 'ROOT/artifacts/transformers'
  plots_path: 'ROOT/plots'
  tracker_path: 'ROOT/model_tracker.csv'