data_paths:
  bicing_data: './data/raw_data'
  meteo_data: './data/meteo_data'
  submission_data: './data/submission_data'
  processed_data: './bike_availability/datasets/'
  stations_to_use_path: ./bike_availability
